// AUTO-GENERATED by packages/database/scripts/gen-marketplace-catalog.ts — do not edit by hand.
// This is a committed placeholder (empty array). Run `gen:catalog` in packages/database
// after applying DB migrations to populate it with live gateway models.
import type { CatalogModel } from './catalog';

export const GENERATED_CATALOG: CatalogModel[] = [];
