-- 0060_tma_own_org.sql
-- Split step 1 (docs/superpowers/plans/2026-07-17-split-web-tma.md, Task 1): give
-- Agents Market (TMA) its own organization, gateway API key, and wallet, instead of
-- sharing the "Gateway Test Org" (00000000-0000-0000-0000-000000000001) with the
-- playground and e2e-test keys. Founder decision 2026-07-17: web (RF aggregator) and
-- TMA (foreign entity) are two different projects; the aggregator becomes a *provider*
-- and TMA a normal *client* with its own org/key/wallet. This is the first step.
--
-- WHY THIS WAS NEEDED (prod fact, verified via SELECT before writing this file):
--   Three keys — playground-system-key, aiag-house-agent-worker (TMA's live money
--   path), e2e-test — all live in org 00000000-…-0001, sharing ONE wallet
--   (subscription_credits=737.74, payg_credits=1000.00 at time of writing) and
--   competing for the same `FOR UPDATE` row lock. Worse: aiag-house-agent-worker has
--   NO daily_usd_cap and NO cost_limit_monthly_rub at all — a live production key
--   with zero blast-radius limit.
--
-- WHAT THIS MIGRATION DOES (idempotent — there is no migration-tracking table on
-- prod, so this file guards every statement and is safe to re-run):
--   1. Synthetic owner user 'agents-market@aiag.local' — same pattern as the existing
--      'gateway-test@aiag.local' service account, not a real login.
--   2. Organization slug='agents-market', fixed id so agent-worker config /
--      docs / the runbook can reference it deterministically. BOTH credit buckets
--      start at ZERO (founder decision: fund manually, after the split is verified
--      end-to-end — every TMA run will honestly 402 until then, per Task 2).
--   3. A new gateway_api_key for agent-worker's live money path, replacing the
--      shared 'aiag-house-agent-worker' key for TMA's traffic going forward (the old
--      key is left untouched in the old org — it is the rollback path, see Task 1
--      "Global Constraints": do not touch org …0001 or its keys in this task).
--      Capped this time: daily_usd_cap=20.00 USD, cost_limit_monthly_rub=15000.00 —
--      see the operator report for sizing rationale; these are a starting safety
--      rail, not a measured number, and are trivially adjustable via UPDATE later.
--
-- SECRET HANDLING (do not skip): the plaintext API key is NEVER generated by this
-- file and NEVER committed to the repo. Generate it at apply time with the SAME
-- algorithm as packages/api-gateway/src/lib/api-key.ts / apps/web/src/lib/dashboard
-- /api-key.ts (`sk_aiag_<env>_<24-random-bytes-base64url>`, SHA-256 hex hash, first
-- 20 chars as prefix) and pass the hash/prefix in as psql variables:
--
--   node -e "
--     const c = require('crypto');
--     const raw = c.randomBytes(24).toString('base64url');
--     const key = 'sk_aiag_live_' + raw;
--     const hash = c.createHash('sha256').update(key).digest('hex');
--     console.log('KEY (put in env, shown once):', key);
--     console.log('HASH:', hash);
--     console.log('PREFIX:', key.slice(0, 20));
--   "
--
--   sudo -u postgres psql aiag \
--     -v key_hash="<HASH from above, unquoted>" \
--     -v key_prefix="<PREFIX from above, unquoted>" \
--     -f 0060_tma_own_org.sql
--
-- If key_hash/key_prefix are not passed, the INSERT below fails with a SQL syntax
-- error (unset `:'var'` is left as literal `:'var'` text) — fails closed, not silent.
--
-- Re-running: statements 1-2 are ON CONFLICT-guarded. Statement 3 is guarded by
-- (org_id, name, revoked_at IS NULL) rather than key_hash, because key_hash is
-- different on every re-run (a freshly generated key) — we do NOT want a re-run to
-- silently mint a second live key for the same purpose.

BEGIN;

-- 1. Synthetic owner (mirrors gateway-test@aiag.local precedent).
INSERT INTO users (email, name)
VALUES ('agents-market@aiag.local', 'Agents Market (TMA) — service account')
ON CONFLICT (email) DO NOTHING;

-- 2. Organization — both credit buckets = 0 (founder decision, funded manually later).
INSERT INTO organizations (id, slug, name, owner_id, subscription_credits, payg_credits)
SELECT
  '00000000-0000-0000-0000-000000000002'::uuid,
  'agents-market',
  'Agents Market (TMA)',
  u.id,
  0,
  0
FROM users u
WHERE u.email = 'agents-market@aiag.local'
ON CONFLICT (id) DO NOTHING;

-- 3. Gateway API key for agent-worker's live money path.
INSERT INTO gateway_api_keys (
  org_id, name, key_hash, key_prefix, rpm_limit, daily_usd_cap, cost_limit_monthly_rub
)
SELECT
  o.id,
  'aiag-house-agent-worker-tma',
  :'key_hash',
  :'key_prefix',
  600,
  20.00,
  15000.00
FROM organizations o
WHERE o.slug = 'agents-market'
  AND NOT EXISTS (
    SELECT 1 FROM gateway_api_keys k
    WHERE k.org_id = o.id
      AND k.name = 'aiag-house-agent-worker-tma'
      AND k.revoked_at IS NULL
  );

COMMIT;
