import createNextIntlPlugin from 'next-intl/plugin';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const withNextIntl = createNextIntlPlugin('./src/i18n/request.ts');

// Legacy /marketplace/... URLs whose slug changed (white-label cleanup —
// routing-layer suffixes like "-kie" stripped, duplicate listings merged).
// Generated by packages/database/scripts/gen-marketplace-catalog.ts —
// re-generate that script's output to keep this list in sync, do not edit
// by hand. `createRequire` is used because next.config.mjs runs as plain
// ESM/Node before the Next.js loader chain is available for JSON imports.
const require = createRequire(import.meta.url);
const legacyMarketplaceRedirects = require(
  './src/lib/marketplace/legacy-redirects.generated.json'
);

// Contest contour removal (2026-09-30): the contests surface moved to Arena,
// so the old Aggregator URLs must not 404 — they 301 to the surviving
// equivalent. Hand-maintained, unlike the generated marketplace list above.
const contestRedirects = [
  { source: '/contests', destination: '/marketplace' },
  { source: '/contests/:path*', destination: '/marketplace' },
  { source: '/admin/contests', destination: '/admin' },
  { source: '/admin/contests/:path*', destination: '/admin' },
  { source: '/contest-host-agreement', destination: '/author-agreement' },
  // Same removal wave: these participant/contest pages went away too.
  { source: '/dashboard/submissions', destination: '/dashboard' },
  { source: '/dashboard/wins', destination: '/dashboard' },
  { source: '/admin/moderation/submissions', destination: '/admin/moderation/models' },
];

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  outputFileTracingRoot: fileURLToPath(new URL('../../', import.meta.url)),
  transpilePackages: ['@aiag/database', '@aiag/tinkoff', '@aiag/shared', '@aiag/api-gateway', '@aiag/upstream-adapters'],
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'storage.yandexcloud.net',
      },
      {
        protocol: 'https',
        hostname: 'avatars.githubusercontent.com',
      },
      {
        protocol: 'https',
        hostname: 'lh3.googleusercontent.com',
      },
    ],
  },
  serverExternalPackages: ['@neondatabase/serverless'],
  poweredByHeader: false,
  compress: true,
  async redirects() {
    return [...legacyMarketplaceRedirects, ...contestRedirects].map((r) => ({
      source: r.source,
      destination: r.destination,
      permanent: true,
    }));
  },
};

export default withNextIntl(nextConfig);
