import { createHash,createPrivateKey,sign } from 'node:crypto';
import { beginCell,storeStateInit } from '@ton/core';
import { WalletContractV4,WalletContractV5R1 } from '@ton/ton';
import { keyPairFromSeed } from '@ton/crypto';
import { describe,expect,it,vi } from 'vitest';
import { verifyTonWalletProof } from '../ton-wallet-proof';
const hash=(b:Uint8Array)=>createHash('sha256').update(b).digest();
function fixture(version:'v4r2'|'v5r1'='v4r2'){
 const seed=Buffer.alloc(32,7),pair=keyPairFromSeed(seed),wallet=(version==='v4r2'?WalletContractV4:WalletContractV5R1).create({workchain:0,publicKey:pair.publicKey});
 const expected={domain:'app.example.test',payload:'aiag:ton-connect:link:-3:'+'a'.repeat(64),network:'-3' as const,issuedAtMs:1790684800123,expiresAtMs:1790684920123,nowMs:1790684811000};
 const timestamp=1790684810,address=wallet.address.toRawString(),domain=Buffer.from(expected.domain),wc=Buffer.alloc(4),len=Buffer.alloc(4),time=Buffer.alloc(8);wc.writeInt32BE(0);len.writeUInt32LE(domain.length);time.writeBigUInt64LE(BigInt(timestamp));
 const body=Buffer.concat([Buffer.from('ton-proof-item-v2/'),wc,wallet.address.hash,len,domain,time,Buffer.from(expected.payload)]);
 const digest=hash(Buffer.concat([Buffer.from([255,255]),Buffer.from('ton-connect'),hash(body)]));
 const privateKey=createPrivateKey({key:Buffer.concat([Buffer.from('302e020100300506032b657004220420','hex'),seed]),format:'der',type:'pkcs8'});
 return {expected,input:{address,network:'-3',publicKey:pair.publicKey.toString('hex'),walletStateInit:beginCell().store(storeStateInit(wallet.init)).endCell().toBoc().toString('base64'),proof:{timestamp,domain:{lengthBytes:domain.length,value:expected.domain},payload:expected.payload,signature:sign(null,digest,privateKey).toString('base64')}},pair,wallet,digest,version};
}
describe('bounded local TON wallet proof verification',()=>{
 it.each(['v4r2','v5r1'] as const)('accepts independently signed %s address proof',version=>{const f=fixture(version);expect(verifyTonWalletProof(f.input,f.expected)).toMatchObject({address:f.input.address,network:'-3',publicKey:f.input.publicKey,walletVersion:version});});
 it('accepts canonical timestamp string with the same signed byte layout',()=>{const f=fixture();expect(verifyTonWalletProof({...f.input,proof:{...f.input.proof,timestamp:String(f.input.proof.timestamp)}},f.expected).address).toBe(f.input.address);});
 it.each(['network','address','publicKey','walletStateInit','signature','payload','domain','lengthBytes','timestamp'])('rejects tampering with %s',field=>{const f=fixture(),input=structuredClone(f.input);if(field==='network')input.network='-239';else if(field==='address')input.address='0:'+'1'.repeat(64);else if(field==='publicKey')input.publicKey='0'.repeat(64);else if(field==='walletStateInit')input.walletStateInit=beginCell().storeUint(0,1).endCell().toBoc().toString('base64');else if(field==='signature')input.proof.signature=Buffer.alloc(64).toString('base64');else if(field==='payload')input.proof.payload+='b';else if(field==='domain')input.proof.domain.value='evil.example.test';else if(field==='lengthBytes')input.proof.domain.lengthBytes++;else input.proof.timestamp++;expect(()=>verifyTonWalletProof(input,f.expected)).toThrow('TON_WALLET_PROOF_INVALID');});
 it.each(['01790684810','1790684810\n','1.79068481e9','9007199254740993',1790684810.5,1790684810000])('rejects noncanonical or millisecond timestamp %s',timestamp=>{const f=fixture();expect(()=>verifyTonWalletProof({...f.input,proof:{...f.input.proof,timestamp}},f.expected)).toThrow();});
 it.each(['expired','future','before-issue'])('rejects stale/future proof by DB-derived %s boundary',mode=>{const f=fixture();const e=mode==='expired'?{...f.expected,nowMs:f.expected.expiresAtMs}:mode==='future'?{...f.expected,nowMs:f.input.proof.timestamp*1000-31000}:{...f.expected,issuedAtMs:f.input.proof.timestamp*1000+1000};expect(()=>verifyTonWalletProof(f.input,e)).toThrow();});
 it('refuses unknown contract code even with a valid key at a plausible offset',()=>{const f=fixture();const fake=beginCell().storeUint(0,32).storeUint(0,32).storeBuffer(f.pair.publicKey).endCell();const state=beginCell().store(storeStateInit({code:beginCell().storeUint(1234,32).endCell(),data:fake})).endCell();expect(()=>verifyTonWalletProof({...f.input,address:'0:'+state.hash().toString('hex'),walletStateInit:state.toBoc().toString('base64')},f.expected)).toThrow();});
 it.each(['state-extra','signature-whitespace','oversized-state','extra-field','exotic','roots'])('rejects invalid bounded input %s',kind=>{const f=fixture();let input:unknown=f.input;if(kind==='state-extra')input={...f.input,walletStateInit:f.input.walletStateInit+'\n'};if(kind==='signature-whitespace')input={...f.input,proof:{...f.input.proof,signature:f.input.proof.signature+'\n'}};if(kind==='oversized-state')input={...f.input,walletStateInit:'A'.repeat(20000)};if(kind==='extra-field')input={...f.input,trusted:true};if(kind==='exotic')input={...f.input,proof:{...f.input.proof,signature:''}};if(kind==='roots'){const header=Buffer.from(f.input.walletStateInit,'base64');header[7]=2;input={...f.input,walletStateInit:header.toString('base64')};}expect(()=>verifyTonWalletProof(input,f.expected)).toThrow();});
 it('bounds BoC claimed cell count before decoder allocation',()=>{const f=fixture(),b=Buffer.alloc(32);b.writeUInt32BE(0xb5ee9c72);b[4]=4;b[5]=4;b.writeUInt32BE(0x7fffffff,6);expect(()=>verifyTonWalletProof({...f.input,walletStateInit:b.toString('base64')},f.expected)).toThrow();});
 it('never evaluates getters or serializes arbitrary input',()=>{const f=fixture();let hit=0;const input=Object.defineProperty({...f.input},'walletStateInit',{enumerable:true,get(){hit++;return f.input.walletStateInit;}});expect(()=>verifyTonWalletProof(input,f.expected)).toThrow();expect(hit).toBe(0);});
 it('does not perform an RPC fallback',()=>{const f=fixture(),fetcher=vi.spyOn(globalThis,'fetch');try{expect(()=>verifyTonWalletProof({...f.input,publicKey:'bad'},f.expected)).toThrow();expect(fetcher).not.toHaveBeenCalled();}finally{fetcher.mockRestore();}});
});
