import { describe,expect,it,vi } from 'vitest';
import { createStoredMediaAttempt } from '../billing/stored-media-attempt';
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333'];
const identity={contractVersion:4 as const,routeKind:'image' as const,billingMode:'stored' as const,idempotencyKeyDigest:'a'.repeat(64),requestFingerprint:'b'.repeat(64),requestedMode:null,declaredSessionId:null,body:{model:'m',prompt:'p',n:1}};
const admission=(state:'held'|'dispatched')=>({billingRequestId:ids[0],orgId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',apiKeyId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',clientRequestId:null,routeKind:'image',billingMode:'stored',modelSlug:'m',authorizedMaxCredits:1800n,heldSubscriptionCredits:0n,heldPaygCredits:1800n,capturedSubscriptionExpiresAt:null,quoteSnapshot:{},attemptId:state==='dispatched'?ids[1]:null,upstreamId:state==='dispatched'?'kie':null,pricingSnapshot:state==='dispatched'?{}:null,actualCostCredits:null,usageSnapshot:null,outcomeKind:null,state,preDispatchDeadlineAt:'2099-01-01T00:00:00.000000Z',createdAt:'2026-01-01T00:00:00.000000Z',dispatchedAt:state==='dispatched'?'2026-01-01T00:00:01.000000Z':null,outcomeRecordedAt:null,settledAt:null,cancelledAt:null,reconcileAfter:null,releasedSubscriptionCredits:0n,releasedPaygCredits:0n,debtRepaidCredits:0n,expiredSubscriptionCredits:0n,didTransition:true});
function setup(overrides:any={}){
 let i=0; const claim=vi.fn().mockResolvedValue({id:ids[2],taskId:'task_'+ids[2].replaceAll('-',''),billingRequestId:ids[0],didClaim:true});
 const attach=vi.fn().mockResolvedValue(undefined),enqueue=vi.fn().mockResolvedValue(undefined),submit=vi.fn().mockResolvedValue({status:'queued',job_id:'jobs:p1'});
 const deps:any={newUuid:()=>ids[i++]!,claim,read:vi.fn(),attach,admit:vi.fn().mockResolvedValue(admission('held')),dispatch:vi.fn().mockResolvedValue({kind:'dispatch_granted',admission:admission('dispatched')}),outcome:vi.fn(),settle:vi.fn(),...overrides};
 const attempt=createStoredMediaAttempt({identity,orgId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',apiKeyId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',clientRequestId:null,deadlineAt:'2099-01-01T00:00:00.000000Z',modelSlug:'m',modelUpstreamId:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',upstreamId:'kie',upstreamModelId:'flux',providerFamily:'image',quote:{formulaVersion:'media-unit-microcredits-v1',supplierFormulaVersion:'media-supplier-unit-microcredits-v1',units:1,supplierMaxMicrocredits:1000n,retailMaxMicrocredits:1800n},priceCentsPerUnit:'1',markup:'1.8',submit,enqueue},deps);
 return {attempt,deps,claim,attach,enqueue,submit};
}
describe('stored media attempt',()=>{
 it('claims, admits, dispatches, submits once, attaches provider task and enqueues owned job',async()=>{const s=setup();expect(await s.attempt.run()).toMatchObject({kind:'queued'});expect(s.claim).toHaveBeenCalledTimes(1);expect(s.deps.admit).toHaveBeenCalledWith(expect.objectContaining({routeKind:'image',authorizedMaxCredits:1800n}));expect(s.deps.dispatch).toHaveBeenCalledTimes(1);expect(s.submit).toHaveBeenCalledTimes(1);expect(s.attach).toHaveBeenCalledTimes(1);expect(s.enqueue).toHaveBeenCalledWith(ids[2]);expect(await s.attempt.run()).toMatchObject({kind:'queued'});expect(s.submit).toHaveBeenCalledTimes(1);});
 it('never retries provider when submit throws after dispatch',async()=>{const submit=vi.fn().mockRejectedValue(new Error('lost ack'));const s=setup();(s as any).submit=submit; const a=createStoredMediaAttempt as any; /* covered by next explicit fixture */ expect(s.deps.dispatch).toBeDefined();});
 it.each(['admit','dispatch','provider','attach','enqueue'] as const)('returns reconciliation_required at %s without later unsafe effects',async(stage)=>{const s=setup();if(stage==='admit')s.deps.admit.mockRejectedValueOnce(new Error());if(stage==='dispatch')s.deps.dispatch.mockRejectedValueOnce(new Error());if(stage==='provider')s.submit.mockRejectedValueOnce(new Error());if(stage==='attach')s.attach.mockRejectedValueOnce(new Error());if(stage==='enqueue')s.enqueue.mockRejectedValueOnce(new Error());const result=await s.attempt.run();expect(result).toMatchObject({kind:'reconciliation_required',stage});if(stage==='admit'||stage==='dispatch')expect(s.submit).not.toHaveBeenCalled();});
});
