import { describe,expect,it,vi } from 'vitest';
import { buildUpstreamPollProcessor } from '../upstream-poll';
const owned={id:'11111111-1111-4111-8111-111111111111',orgId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',billingRequestId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',status:'queued' as const,providerFamily:'image' as const,providerTaskId:'jobs:p1',deadlineAt:Date.now()+60000,quotedRetailMicrocredits:100n,output:null,errorMessage:null,settledAt:null};
function job(data={jobId:owned.id}){return {data,name:'poll',attemptsMade:0,queue:{add:vi.fn()}} as any}
describe('owned upstream poll processor',()=>{
 it('loads DB authority and requeues pending with job id only',async()=>{const q=job();const deps={load:vi.fn().mockResolvedValue(owned),markProcessing:vi.fn(),poll:vi.fn().mockResolvedValue({status:'pending'}),finalize:vi.fn()};expect(await buildUpstreamPollProcessor(deps)(q,'x')).toEqual({status:'pending'});expect(deps.poll).toHaveBeenCalledWith(owned);expect(q.queue.add.mock.calls[0][1]).toEqual({jobId:owned.id});expect(q.queue.add.mock.calls[0][2].jobId).not.toContain(':');expect(deps.finalize).not.toHaveBeenCalled();});
 it('finalizes completed exactly through sink',async()=>{const deps={load:vi.fn().mockResolvedValue(owned),markProcessing:vi.fn(),poll:vi.fn().mockResolvedValue({status:'completed',output:'https://cdn/x'}),finalize:vi.fn()};await buildUpstreamPollProcessor(deps)(job(),'x');expect(deps.finalize).toHaveBeenCalledWith(owned,'completed','https://cdn/x',undefined);});
 it('deadline fails without provider poll',async()=>{const expired={...owned,deadlineAt:Date.now()-1};const deps={load:vi.fn().mockResolvedValue(expired),markProcessing:vi.fn(),poll:vi.fn(),finalize:vi.fn()};expect(await buildUpstreamPollProcessor(deps)(job(),'x')).toMatchObject({status:'failed'});expect(deps.poll).not.toHaveBeenCalled();expect(deps.finalize).toHaveBeenCalled();});
 it('terminal redelivery skips provider and asks DB sink to finish idempotently',async()=>{const done={...owned,status:'completed' as const,output:'https://cdn/x'};const deps={load:vi.fn().mockResolvedValue(done),markProcessing:vi.fn(),poll:vi.fn(),finalize:vi.fn()};await buildUpstreamPollProcessor(deps)(job(),'x');expect(deps.poll).not.toHaveBeenCalled();expect(deps.finalize).toHaveBeenCalledWith(done,'completed','https://cdn/x',undefined);});
 it('rejects claimed job without attached provider task',async()=>{const claimed={...owned,status:'claimed' as const,providerTaskId:null};const deps={load:vi.fn().mockResolvedValue(claimed),markProcessing:vi.fn(),poll:vi.fn(),finalize:vi.fn()};await expect(buildUpstreamPollProcessor(deps)(job(),'x')).rejects.toThrow('MEDIA_PROVIDER_TASK_NOT_ATTACHED');});
});
